### ISSUE TITLE
Port plugin unavailable for YAML

### ISSUE THREAD

**Issue by nstires-ctgx** [port-labs/pulumi-port#31]
Initial template:
```
name: port
runtime: yaml
description: Configuration for getPort.io

resources:
  gcp-proj-deployer:
    type: port:Blueprint
    properties:
      identifier: gcpProjDeploy
      title: GCP Project Deployer
      description: Creates new GCP Project with unique ID and subdomain
      icon: Pulumi
      properties: 
        stringProps:
          environment:
            title: environment
            icon: GoogleCloudPlatform
            required: true
            enums: ["dev", "test", "prod"]
            enumColors:
              dev: yellow
              test: orange
              prod: red
```

Executed:
```
pulumi up
pulumi:pulumi:Stack (port-main):
    Error: error resolving type of resource gcp-proj-deployer: internal error loading package "port": Could not automatically download and install resource plugin 'pulumi-resource-port', install the plugin using `pulumi plugin install resource port`.
    Underlying error: 401 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-port/releases/latest
      on Pulumi.yaml line 7:
       7:     type: port:Blueprint
```

Manual install still fails:
```
pulumi plugin install resource port
error: 401 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-port/releases/latest
```
